### ISSUE TITLE
Add a favicon to the documentation

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/ods-charts#15]
### Description

Our documentation doesn't have any favicon files for now.

To close this issue, a favicon file (or files) should be added to all pages of the documentation.

There could be extra things to do for https://ods-charts.netlify.app/api/.

Don't forget to add the favicon file (or files) to our https://github.com/Orange-OpenSource/ods-charts/blob/main/NOTICE.txt.

### Sub-tasks

- [x] Add favicons images in the repository and mention them in a `NOTICE.txt`
- [x] Add favicons to the documentation
- [ ] Add favicons to the `/api` (we might need something like https://www.npmjs.com/package/typedoc-plugin-extras as an extra plugin to do that)
